# MLflow experiment settings
mlflow:
  experiment_name: "asd_detection"
  tracking_uri: "file:./mlruns"

# Dataset configuration
data:
  dataset_path: "Dataset/processed"      # root folder containing train/valid/test or consolidated
  features_csv: "Dataset/radiomics_features.csv"  # CSV com features extraídas pelo dataset_enhancer.py
  image_height: 224                  # EfficientNet / MobileNet input size
  image_width: 224
  channels: 3
  batch_size: 32
  validation_split: 0.15             # used if folders not pre-split
  test_split: 0.15
  shuffle: true
  seed: 42

# Training hyper-parameters
training:
  epochs: 60
  initial_learning_rate: 0.0003
  optimizer: "adamw"             # adam | adamw | sgd
  weight_decay: 0.01             # 0.01 recomendado para AdamW
  momentum: 0.9                  # usado apenas se optimizer == sgd
  gradual_unfreeze_milestones: [5, 10, 15, 20]  # milestones menores (25% cada)
  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  early_stopping_patience: 5
  early_stopping_min_delta: 0.0005
  early_stopping_monitor: "val_loss"  # val_loss ou val_acc
  reduce_lr_patience: 3
  reduce_lr_factor: 0.5
  k_folds: 3            # >1 enables Stratified K-Fold CV

# Model section
models:
  model_list:
    - "MultimodalResNet"

  vitb16:
    # Parameters forwarded to ViTB16Model.get_default_config / build
    pretrained: true
    dropout: 0.1

    # Data augmentation flags read by DataHandler
    use_data_augmentation: true
    augmentation_intensity: "medium"  # light | medium | strong

  MultimodalResNet:
    # Backbone CNN para transfer learning
    backbone: "resnet50"              # resnet18, resnet50, efficientnet_b0, mobilenet_v3_small
    pretrained: true
    freeze_backbone: false            # congela backbone durante treino inicial
    num_tabular_features: 300         # número de features do CSV (colunas - 2)
    fusion_hidden: 256                # tamanho da camada de fusão
    dropout: 0.3                      # dropout para regularização 